first_name = input("Enter your first name: ").lower()
last_name = input("Enter your last name: ").upper()
email = input("Enter your email address: ").lower()
phone = input("Enter your phone number: ")
job_title = input("Enter your job title: ").title()
id_number = input("Enter your ID Number: ")
hair_color = input("Enter hair color: ").title()
eye_color = input("Enter eye color: ").title()
month = input("Enter starting month: ").title()
experience = input("Do you have experience? (Yes/No) ").title()

print("The ID Card is:")
print("-" * 50)
print(f"{last_name}, {first_name}")
print(job_title)
print(f"ID: {id_number}")
print("")
print(email)
print(phone)
print("")
print(f"{'Hair: ' + hair_color:<30}{'Eyes: ' + eye_color:<30}")
print(f"{'Month: ' + month:<30}{'Experience: ' + experience:<30}")
print("-" * 50)